version: "3.9"

services:
  vdrop:
    build: .
    container_name: vdrop
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./downloads:/app/downloads
    environment:
      - PYTHONUNBUFFERED=1
